pipeline {
  agent any

  parameters {
    gitParameter type: 'PT_BRANCH_TAG',
                 name: 'TAG_OR_BRANCH',
                 defaultValue: 'origin/main',
                 selectedValue: 'NONE',
                 sortMode: 'DESCENDING_SMART',
                 tagFilter: '*'
  }

  stages {
    stage('Build') {
      steps {
        sh './gradlew :engine:build'
      }
    }

    stage('Deploy') {
      steps {
        script {
          def output = sh returnStdout: true, script: './gradlew -q appVersion'
          def appVersion = output.trim()

          sh "sudo cp engine/build/distributions/kastle-${appVersion}.zip /var/www/kastle-docs/attachments/kastle-${appVersion}.zip"
        }
      }
    }

    stage('Cleanup') {
      steps {
        cleanWs cleanWhenAborted: false, cleanWhenFailure: false, cleanWhenNotBuilt: false, cleanWhenUnstable: false
      }
    }
  }
}